; This file describes fixture build properties

[fixtures]
timestamp = 2025-02-14T01:16:17.703506
build = develop
ref = refs/tags/v4.0.0
commit = 2e1d3a0c7ec7a2f02fd7b9ad4900f79e323910f1
command_line_args = fill -n auto --evm-bin=ethereum-spec-evm-resolver --solc-version=0.8.21 --skip-evm-dump --until=Prague --output=fixtures_develop.tar.gz --build-name develop

[packages]
pytest = 7.4.4
pluggy = 1.5.0

[plugins]
metadata = 3.1.1
xdist = 3.6.1
json-report = 1.5.0
custom-report = 1.0.1
html = 4.1.1
typeguard = 4.3.0

[tools]
eels resolutions = /home/marioevz/actions-runner/_work/execution-spec-tests/execution-spec-tests/eels_resolutions.json
t8n = ethereum-spec-evm-resolver 0.0.5
solc = 0.8.21

[environment]
python = 3.10.15
platform = Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
ci = true

